spring.application.name=supply-chain-base-operation
# ===============================
# PostgreSQL (Neon) Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://ep-divine-fog-azxzur6h.c-3.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_2I8EhAloVyLC
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# Hibernate / JPA Configuration
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional (recommended for Neon)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

